language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"
  - "pypy"
before_install:
  - pip install -U pip
  - ./travis_before_install.sh
install:
  - pip install -r requirements.txt
script: python setup.py test
env:
  global:
    - CFLAGS=-I/tmp/include -I/tmp/include/OpenEXR
    - LDFLAGS=-L/tmp/lib
    - LD_LIBRARY_PATH=/tmp/lib
    - LIBRARY_PATH=/tmp/lib
    - PKG_CONFIG_PATH=/tmp/lib/pkgconfig
sudo: false
git:
  depth: 5
