language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"
  - "pypy"
before_install:
  - pip install -U pip
install:
  - pip install -vr requirements.txt
script: python setup.py test
sudo: false
git:
  depth: 5
addons:
 apt:
   packages:
     - libopenexr-dev
     - libopenexr6
