language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"
  - "pypy"
install:
  - pip install -r requirements.txt
script: python setup.py test
sudo: false
git:
  depth: 5
